on:
  workflow_dispatch: {}
name: schema-sync

jobs:
  generate:
    name: Generate Patched Schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set git identity
        run: |-
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Setup Node
        uses: actions/setup-node@main
        with:
          node-version: '*'
        env:
          NODE_OPTIONS: '--max-old-space-size=8196'
      - name: Pull and Patch Schema
        id: pull_and_patch
        uses: TheRealAmazonKendra/cdk-patched-schema-generator@main
        with:
          output-path: '/home/runner/work/cdk-from-cfn/cdk-from-cfn/src/specification'
      - name: Show Diff
        run: 'git diff'
      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          author: github-actions <github-actions@github.com>
          committer: github-actions <github-actions@github.com>
          signoff: true
          branch: github-actions/update-schema
          body: |
            Updates CloudFormation Specification. See details in [workflow run].
            [Workflow Run]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          commit-message: |-
            chore: upgrade cloudformation specification
            Updates CloudFormation Specification. See details in [workflow run].
            [Workflow Run]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          title: 'chore: update cloudformation specification'
          labels: auto-approve
