on:
  workflow_dispatch: {}
name: schema-sync

jobs:
  generate:
    name: Generate Patched Schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set git identity
        run: |-
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Setup Node
        uses: actions/setup-node@main
        with:
          node-version: '*'
        env:
          NODE_OPTIONS: '--max-old-space-size=8196'
      - name: Get Database
        run: |-
          yarn add @aws-cdk/aws-service-spec
          ls
          pwd
          mv node_modules/@aws-cdk/aws-service-spec/db.json.gz db.json.gz
          ls
          pwd
      - name: Pull and Patch Schema
        id: pull_and_patch
        uses: TheRealAmazonKendra/cdk-patched-schema-generator@main
      - name: Update Local Schema Files
        run: |-
          ls
          pwd
          ${{ steps.pull_and_patch.outputs.cdkTypes }} > src/specification/cdk-types.json
          ${{ steps.pull_and_patch.outputs.cdkResources }} > src/specification/cdk-resources.json
