on:
  workflow_dispatch: {}
name: schema-sync

jobs:
  generate:
    name: Generate Patched Schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
      - name: Set git identity
        run: |-
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Pull and Patch Schema
        id: pull_and_patch
        uses: TheRealAmazonKendra/cdk-patched-schema-generator@main
      - name: Update Local Schema Files
        run: |-
          ls
          pwd
          ${{ steps.pull_and_patch.outputs.cdkTypes }} > src/specification/cdk-types.json
          ${{ steps.pull_and_patch.outputs.cdkResources }} > src/specification/cdk-resources.json
